### ISSUE TITLE
Cannot load font-awesome and material-icons

### ISSUE THREAD

**Issue by metallidevils** [CanopyTax/single-spa-angular#101]
Hi,

I have a single-spa-angular website that is mostly working. However no matter where I set the deployUrl, whenever my application tries to download the icons related to material-icons or font-awesome, the app tries to download them from the server hosting the index.html, not the single-spa angular application. Any help would be appreciated!

**Comment by joeldenning** [comment]
Angular 7? Or Angular 8?

**Comment by metallidevils** [comment]
Angular 8. Also same problem with ngx data table. Basically any dependency
that tries to load a font, fails. Everything else works.

**Comment by joeldenning** [comment]
Is this happening during `ng serve` or `ng build`? When I last looked at this, the `--deployUrl` fixed it, but it took me seriously 4 hours to realize that that is what was needed. You might be on your own for this one, because my desire to debug your project for 4 hours is pretty low 😄 

My experience with angular cli is that if you keep on adding cli arguments it sometimes will work.
