### ISSUE TITLE
Trying to understand why MiniCssExtractPlugin is manually removed

### ISSUE THREAD

**Issue by metallidevils** [CanopyTax/single-spa-angular#106]
Hi,

I am looking at the example webpack config here: 

https://github.com/CanopyTax/single-spa-angular/blob/b8b4daf87af4100935f6febee31a715d8e7529c8/src/builders/single-spa-webpack-builder.ts

I'm trying to understand the need for

  removePluginByName(mergedConfig.plugins, 'IndexHtmlWebpackPlugin');
  removeMiniCssExtract(mergedConfig);

I understand that the systemjs import will not work if these plugins are used. However, where is the actual configuration that adds these plugins to begin with? Are they added by default by Angular?

**Comment by filoxo** [comment]
I think they're added to the webpack config by default when generated using the angular-cli. See https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts#L21
I have no idea where this resides in the generated project.

**Comment by joeldenning** [comment]
The reason for removing IndexHTMLWebpackPlugin:

single-spa applications do not have their own html files. They all share one html file. This is why it is called "single" spa (there's only one SPA).

The IndexHTMLWebpackPlugin creates an html file for each application, which is not needed nor usable in the single-spa architecture.

The reason for removing MiniCssExtractPlugin:

The MiniCssExtractPlugin creates css files that must be loaded via `<link href="/path-to-file.css">`. This is generally done by automatically injecting a `<link>` inside of the html file generated by IndexHTMLWebpackPlugin. As described above, in a single-spa architecture there is only one html file for all applications, and it is not generated by webpack. The decision to remove MiniCssExtractPlugin is so that users of single-spa-angular don't have to manually inject a `<link>` element to the page to load their css.
