### ISSUE TITLE
CORS policy" blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by born2excite** [CanopyTax/single-spa-angular#108]
Any help is much appreciated :)

### Problem
Access to script at https://platform-api.sharethis.com/js/sharethis.js
is blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

**Proposed fix**
I've enabled CORS on the Origin Server for static resources, including js but the js from sharethis is still being blocked. so, I'm wondering if I can add a second CORS policy to specifically allow js from sharethis. For example, adding:

`Header set Access-Control-Allow-Origin: https://platform-api.sharethis.com/js/sharethis.js`

to my current CORS policy:

```
Current CORS policy in .htaccess file:
<IfModule mod_setenvif.c>
  <IfModule mod_headers.c>
    <FilesMatch "\.(bmp|cur|gif|ico|jpe?g|png|svgz?|webp|ttf|ttc|otf|eot|woff|woff2|font.css|css|js)$">
      SetEnvIf Origin ":" IS_CORS
      Header set Access-Control-Allow-Origin "*" env=IS_CORS
    </FilesMatch>
  </IfModule>
</IfModule>
```
**Question**

- Is adding a second CORS policy possible? 
- If it is, how?
- Alternatively, is there a better way?

BIG thanks for any suggestions / help!
Julian

**Comment by joeldenning** [comment]
This issue doesn’t seem related to single-spa at all?

I don’t know what https://platform-api.sharethis.com/js/sharethis.js is. If all you are trying to do is execute it is a JavaScript file, I’d recommend just using a script tag for it, since script tags do not require CORS in order to work. Only fetch/Ajax requires cors.

I’m closing this because I see no connection to single-spa here. Feel free to comment further or reopen if I’m missing something.
