### ISSUE TITLE
Angular doesn't trigger detect changes between coexisting microfrontends

### ISSUE THREAD

**Issue by Magefo** [CanopyTax/single-spa-angular#114]
The problem is related to detect changes on angular projects, when you build a portal and at least two angular microfrontends, when you fire an event in the mf1 and the mf2 is listening through router change or single spa update lifecycle the mf2 doesn't updte until you interact with it.

**Comment by joeldenning** [comment]
Hi Magefo - the bug you've reported here is one that we've seen periodically for about 4 years. We have put in several workarounds in the past and then taken them out when they don't quite work out. This has been previously discussed in https://github.com/CanopyTax/single-spa-angular/issues/86

Our current workaround is this:

https://github.com/CanopyTax/single-spa-angular/blob/master/src/browser-lib/single-spa-angular.ts#L61

The problem is that change detection through ZoneJS + Angular is really finnicky. The way that Angular implemented zonejs via the core angular libraries actually assumes that there is only ever one angular application on the page at any point in time. Single-spa-angular goes to [pretty great lengths](https://github.com/CanopyTax/single-spa-angular/blob/3082db78b504f225b1ee4e6462868eba35c9ca23/src/browser-lib/single-spa-angular.ts#L54) to get angular + zonejs to not freak out about multiple angular applications. However, with all of those workarounds, things are still not perfect.

Another related issue is https://github.com/CanopyTax/single-spa-angular/issues/113

**Comment by Magefo** [comment]
thank you!

**Comment by christcottrell** [comment]
It looks like this has been closed for a while, but the link to the current work around is no longer working. Thanks!
