### ISSUE TITLE
ZoneJS error when opening application with /:id route

### ISSUE THREAD

**Issue by arnevdv** [CanopyTax/single-spa-angular#120]
There seems to occure an error when I load an angular microservice directly. This error does not occure when I navigate to a route from within that microservice with `this.router.navigateByUrl('/microfrontend/' + data.id)`

So if I load for example this url (with example id 12345) from scratch: http://www.wrapper.com/microfrontend/12345, i got the following error.

![image](https://user-images.githubusercontent.com/15064170/70058434-3045ea00-15df-11ea-92b4-547ebeaab611.png)

Below you can watch the order of my steps. I have not been able to reproduce this in the example application...

![image](https://im.ezgif.com/tmp/ezgif-1-994572ea576a.gif)

I've been looking to fix this issue for several days. Any idea's or solutions are more than welcome..

**Comment by joeldenning** [comment]
This error usually means that you're trying to download a json file but it's actually downloading an html file. The way that that happens is when the server is configured to always return the index html file for all pages, which is what is used for SPAs.

To diagnose, I'd look in the network tab of the devtools and find the request that is causing this. It will likely have an HTTP status of 200, but will return the index html file instead of the json or javascript that it should have. My guess is that that request is going to the wrong server entirely and that the reason is the [webpack public path](https://single-spa.js.org/docs/faq/#code-splits)

**Comment by arnevdv** [comment]
You gave me a hint in the right direction. In the index.html file there was a backslash missing to import my importmap.json.

This
`<script type="systemjs-importmap" src="importmap.json"></script>`
pointing to
`http://www.wrapper.com/microfrontend/importmap.json`

instead of 
`<script type="systemjs-importmap" src="/importmap.json"></script>`
pointing to
`http://www.wrapper.com/importmap.json`

This issue can be closed. Thanks! :)

**Comment by joeldenning** [comment]
👍 glad to hear that you got it working
