### ISSUE TITLE
add conventional commits

### ISSUE THREAD

**Issue by cgatian** [CanopyTax/single-spa-angular#19]
Enforce [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.3/) with [commitLint](https://conventional-changelog.github.io/commitlint/#/)
Autogen changlog with [standard-version](https://github.com/conventional-changelog/standard-version)

**Comment by joeldenning** [comment]
The more I've thought this over, the less I feel good about it. I don't like when projects put potential contributors through a bunch of hurdles in order for them to get the build to pass. I think it discourages contribution and shifts focus away from important things (like whether this is good code) towards things that don't really matter much (like if all the linting and CLA and commit messages are exactly the same as if i had done them).

What I have done in the past for single-spa-angular and the dozens of other open source projects that I maintain is just manually create release notes by looking at the commits and PRs since the last release. I have not found that process painful -- i'd rather not introduce a solution to a pain that doesn't exist.

See [this section of this blog article](https://overreacted.io/writing-resilient-components/#dont-get-distracted-by-imaginary-problems), which explains further how I feel about this.

**Comment by cgatian** [comment]
Thats unfortunate. Conventional commits enforce a standard that make the developer "think" before they commit.  

Take for example the latest contribution:
![image](https://user-images.githubusercontent.com/1752170/54859374-bbe24980-4ce2-11e9-8b57-5a6187696d06.png)
It forces the developer to take a step back and 6think, what is exactly being modified?

IMO not having this leads to commits like "added semi colon", "did stuff".

Im pretty passionate about this, as it adds to the craftsmanship and quality of the code produced. It forces developers to create isolated pieces of work that add incremental value. AKA iteration :)

**Comment by joeldenning** [comment]
Sounds like we disagree 😄 

We can talk over slack if you'd like -- I am not convinced that it is solving a real problem.

**Comment by cgatian** [comment]
This project doesnt generate a CHANGLOG. It probably should 👍 . This would help.

**Comment by joeldenning** [comment]
I personally prefer using Github releases over a Changelog, although the preference isn't super strong. I have kept the github releases fully up-to-date with release notes. https://github.com/CanopyTax/single-spa-angular/releases. Maybe making a CHANGELOG.md file that just links to the github releases page would be a good idea though.

I'm going to close this issue, since I don't want to use or enforce conventional commits in this project. If you disagree very strongly about this, let's talk over slack or video call and we can sort it out.
