### ISSUE TITLE
schematic: root

### ISSUE THREAD

**Issue by cgatian** [CanopyTax/single-spa-angular#29]
Generate a root application to host single-spa apps.

**Comment by joeldenning** [comment]
See https://github.com/CanopyTax/single-spa-angular#check-if-it-works for a minimal root application that could get people started.

**Comment by joeldenning** [comment]
I spent a few hours on this yesterday and ran into some tough roadblocks with angular schematics. Specifically that angular schematics only allow you to create files that are within your angular project, but that we need the single-spa root config html file to be in `../single-spa-root-config` which is not in the angular project at all.

I'm going to close this for now, since I don't plan on implementing this in the near future. If @cgatian or anyone else would like to PR an implementation for this, I'm happy to review it.
