### ISSUE TITLE
polyfills and styles bundles are not created any more

### ISSUE THREAD

**Issue by jongeuncha** [CanopyTax/single-spa-angular#35]
With this commit, [feat(builder): Angular CLI builder for bundling single module](https://github.com/CanopyTax/single-spa-angular/commit/5761fd10a8c81d3b7e80dfc4e45ca4bb89350575), `polyfills` and `styles` entries are removed and these bundles are not built anymore, which are essential to our application.

**Comment by joeldenning** [comment]
For polyfills, this was actually an intended change. I think it is best to try to move polyfills into the [single-spa root config](https://github.com/CanopyTax/single-spa-angular#check-if-it-works), so that you only load them once upfront instead of once per angular application. The biggest one is usually ZoneJS, and with Zone you actually have no choice but to only have one instance of it on the page.

For styles, our goal was to get all the styles to be baked into the `main.js` file as javascript strings that turn into `<style>` elements when the javascript executes. Is that not what you're seeing?

**Comment by jongeuncha** [comment]
I understand your intention but I think how to manipulate and deploy bundles should be up to the consumers and yes I would like to serve the polyfills in the root application and will serve `main.js` and `style.js` in the Angular application.

If the `styles.js` is combined into `main.js`, it sounds convenient but it limits the freedom and especially it does not conform to our deployment strategy.

**Comment by joeldenning** [comment]
Could you provide more info about your deployment strategy?

One problem that I face as a maintainer of single-spa is that everyone's deployment strategy is different and it is hard to find the best balance between being opinionated and being flexible. Full flexibility means I spend a lot of time in issue queues trying to figure out the specifics of someone's situation, whereas opinionated means that there's a nice happy path for most people to follow.

`ng add single-spa-angular` is opinionated in how the build happens because then the documentation can be less complex about how to use it. There is always the option to do `npm install --save single-spa-angular` if you'd rather not have the builder, or to modify your angular.json file manually to use a different builder.

Alternatively, I am open to adding an option to single-spa-angular's `ng-add` process that would make it produce separate css files instead of all inside of the js file. This opens up future complexity for me because then people will have trouble getting their single-spa root config to always have the correct url for the css file in both local development and deployed environments. But I agree it would be a nice option to have.

I likely wouldn't get around to implementing this in the immediate future, but the basic implementation approach would be to add the [extract loader](https://webpack.js.org/loaders/extract-loader/#extracting-a-maincss) to our [webpack config](https://github.com/CanopyTax/single-spa-angular/blob/master/src/builders/browser/index.ts#L47), but only if the user opts into it. Pull requests are definitely accepted, see the [contributing docs](https://github.com/CanopyTax/single-spa-angular/blob/master/CONTRIBUTING.md) for how to get started.

**Comment by joeldenning** [comment]
See related #46, where I added the styles into the main bundle so that they work with single-spa-angular. I decided it was easier just to put the global styles right into the main.js bundle instead of having a separate webpack entry for them and having to load them separately from the javascript bundle.

Regarding the polyfills, my recommendation is the same as what I said before -- ZoneJS and polyfills should be loaded inside of the [single spa root application](https://github.com/CanopyTax/single-spa-angular#check-if-it-works) (also see these related [docs](https://single-spa.js.org/docs/configuration.html)).

I am closing this issue -- feel free to reopen or comment further with more questions.
