### ISSUE TITLE
[Brainstorm] Multiple versions of Zone JS and Angular for different child applications

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/single-spa-angular#4]
@daniele-zurico is the one who has been researching this the most. The basic problem is that if you want to have multiple versions of ZoneJS (one for each child application that uses Angular), we don't know of a way to do that. This is because ZoneJS creates a global variable `window.Zone` that would clash if you loaded the Zone library.

Note that the recommended approach is to have a shared version of Zone and Angular that different single-spa child applications share. But that this issue is talking for when that is not desired.

My newest idea for how to potentially solve this is a SystemJS-specific solution that I'm not totally sure about. It involves:
1) Tell SystemJS not to let the Angular child application leak the `Zone` global variable
2) Tell SystemJS to provide the Angular child application a shimmed `Zone` global variable whenever it is referenced.

I believe that doing this is possible and would require a combination of the SystemJS configuration options for shimming dependencies, custom globals, and exports

**Comment by Slash7GNR** [comment]
Hey @joeldenning ,
Anything new with this issue?
Right now we have a requirement that we can have different application with different angular versions (for example, one app with angular 4 and another with angular 5), we have this requirement to let different teams to upgrade angular versions in their own comfortable time.
I researched this issue a bit in the micro-frontend world, and it seems that in case you have such a requirement, the only solution for this will be using iframes, for a full isolation, since all the other solutions share the same DOM, and then you'll have problems to have different versions of a framework (I understood that you'll have the same problem if you will use react for example).
What do you think?

Thanks,
Nadav

**Comment by joeldenning** [comment]
Yeah, iframes would solve this, although there is at least one company doing so that deeply regrets it because of the performance implications. cc @leandromiranda

Is it possible to have multiple versions of Angular but only one shared zone.js instance? Or are there frequent breaking changes with Zone.js that would prevent that?

If that is possible, that is the place I would start, I think.

**Comment by robinComa** [comment]
I think there is no problem to share one version of zone.js. It don’t often change.
It is what I’ve done here :
https://www.npmjs.com/package/single-spa-angular-cli

**Comment by adrianromanko** [comment]
There will always be js libraries that force themselves into the global namespace such as zone.js.
Angular 2/4 releases should be paired with a specific version of zone.js and we cannot assume that the root container will have backwards compatibility for future releases.
This is something that needs to be resolved going forward if we want multiple micro frontends to coexist  and be properly scoped without having to worry global collisions.

**Comment by joeldenning** [comment]
@adrianromanko do you have any ideas for how to get two separate versions of ZoneJS working together on the same page?

**Comment by adrianromanko** [comment]
Using iFrames would be the only workaround. Expose an event bus or API for the root SPA that would essentially be a bunch of event handlers for the child apps. I'm aware of a few issues with iframes (resizing, blurry after rendering. What would you say are the biggest trade offs?

**Comment by daniele-zurico** [comment]
To fix the zoneJs problem the only way you have is to import it in the main app the latest version of zoneJs and exclude from the compilation of the children app zoneJs.
Until now zoneJs didn’t create breaking changes but everyone know that it could happen and at that point you can’t upgrade anymore.
If you go with a iframe solution I suggest you to look on comlink (from google) that wrap post messages in the library.
I tried both approaches and I can tell you if you’re using angular the second option is suggested.
With framework/libraries like react you can go with canopy
Bear in mind that you’ll have the same problem for all the libraries that use window like jquery etc

**Comment by joeldenning** [comment]
I have consulted with a company that went the iframes approach and regrets it because of performance -- I think that having one instance of ZoneJS shared across all applications is much more performant than iframes.

**Comment by nickfeng1982** [comment]
the best solution to deal with zone.js issue so far is

1, comment out import 'zone.js/dist/zone'; from the pollyfill.ts
2, add <script src="https://cdnjs.cloudflare.com/ajax/libs/zone.js/0.8.29/zone.js"></script> into the index.html

since angular will compile zone.js into the bundle so this way the spa framework won't load zone.js from the child, and only the shell has one zone.js file acting.

by the way, iframe is another approach for micro front ends, if anyone wants to go with that routes, you don't need to look into single spa in my opinions, but of course, iframes will bring another set of issues, maybe they are harder to deal with for a business solution.
#

**Comment by joeldenning** [comment]
Agreed with @nickfeng1982 -- see [this documentation](https://github.com/CanopyTax/single-spa-angular/blob/60b88f90d90a6bcbe7e1d1e751c521c48e39f705/README.md#check-if-it-works) which encourages loading ZoneJS directly in the single-spa root config html file, instead of inside of polyfills.ts within an angular application. See related #35 for discussion on that.

I am closing this for now: the official, encouraged solution is to move ZoneJS into your single-spa root config html file so that it's only loaded once.
