### ISSUE TITLE
AOT build and Ivy compiler

### ISSUE THREAD

**Issue by HemendPatel63** [CanopyTax/single-spa-angular#52]
I have tried to implement angular ivy compiler with the latest version on single-spa angular but not able to compile the project. is it support ivy compiler (@angular/cli v8.0.0-beta.7)?

**Comment by joeldenning** [comment]
I have not tried an aot build with angular 8. Could you provide a stacktrace or describe the error in more detail?

**Comment by HemendPatel63** [comment]
I am getting bellow error : 

![image](https://user-images.githubusercontent.com/49240619/55925713-1250f280-5bd4-11e9-8f3c-6c92541cca98.png)

**Comment by joeldenning** [comment]
The stacktrace is probably being caused by one of the following lines of code:

https://github.com/CanopyTax/single-spa-angular/blob/master/src/single-spa-angular.ts#L80
https://github.com/CanopyTax/single-spa-angular/blob/master/src/single-spa-angular.ts#L93
https://github.com/CanopyTax/single-spa-angular/blob/master/src/single-spa-angular.ts#L122

I don't know much about aot compilation -- does it make the dependency injector not available in the browser? Could be a variety of things that cause the issue. Angular 8 support isn't my top priority right now, since I'm still trying to get Angular@<=7 to work. But when those become stable, I could revisit Angular 8

About sharing data between applications, here is an issue you can look at. Sort of older, but still relevant: https://github.com/CanopyTax/single-spa/issues/107#issuecomment-325475260

**Comment by HemendPatel63** [comment]
AOT compilation is not an issue as I am successfully build single spa angular 7 app with AOT. I think issue is with ivy compiler. 
Thank you so much for you quick help!

**Comment by joeldenning** [comment]
👍 I'll keep this issue open so that when angular <=7 is supported I can come back to this

**Comment by HemendPatel63** [comment]
I have gone through the link CanopyTax/single-spa#107 (comment) but we have to give refresh of individual app. suppose my core app display different module and have a summary section as separate app where will display specific module summary then have to give reference of each core app.

![image](https://user-images.githubusercontent.com/49240619/56002849-a761f300-5c89-11e9-95fa-ea5edc323d5b.png)

I was checking for other option and came across -https://github.com/me-12/single-spa-portal-example solution where we are injecting the globalEventDistributor to manage the state between applications. I have tried to do the same thing but getting exception as I think we need optional parameter to inject this. 

![image](https://user-images.githubusercontent.com/49240619/56003001-4be43500-5c8a-11e9-8c3b-032b386561b3.png)

**Comment by HemendPatel63** [comment]
I have used deepstreamHub to do this

**Comment by cleisommais** [comment]
I had the same issue, however, if you change the version only "@angular-devkit/build-angular" and "@angular/cli" devDependencies you will fix the issue. In my case, are 4 different Angular 8 projects with Material Design and Google Charts, after correct changes everything works fine.
The dependencies with the new version:

-     "@angular-devkit/build-angular": "~0.13.0",
-     "@angular/cli": "~7.3.6",
