### ISSUE TITLE
Router not working without APP_BASE_HREF

### ISSUE THREAD

**Issue by kbjerke** [CanopyTax/single-spa-angular#64]
Hi, @joeldenning 

Based on your comment in #62 I made a few changes to my fork: [remove-app-base-href](https://github.com/kbjerke/coexisting-angular-microfrontends/tree/remove-app-base-href), you can compare it to the master branch, only difference is removal of APP_BASE_HREF providers in app1 and app2. 

Without APP_BASE_HREF an empty path, indicating the root of this specific application will simply redirect to the root of the single-spa app. So a router configuration like:
```
const routes: Routes = [
  { path: '', pathMatch: 'full', component: EmptyRouteComponent },
  { path: 'subroute', component: SubrouteComponent },
  { path: '**', redirectTo: '' },
];
```
will not work.

I also removed BrowserAnimationsModule from app1 and AnimationEngine from the singleSpaAngular options in app1/src/main.single-spa.ts, because it was causing issues with lazy loading, possibly related to: https://github.com/angular/angular/pull/20719, but I haven't found it reference in a ticket.

EDIT:
This answer mentions it https://stackoverflow.com/a/45660781

**Comment by joeldenning** [comment]
I'll take a look at this after I finish single-spa-playground and resolve #44 and #41

**Comment by kbjerke** [comment]
Hi @joeldenning , I created this repo: [microfrontend-communication](https://github.com/kbjerke/microfrontend-communication), in app2 I have imported `BrowserAnimationsModule` and you can easily reproduce the issue of routes being appended rather than replacing.

**Comment by joeldenning** [comment]
I am on vacation right now but will take a look at this as one of my top single-spa-angular issues when I get back in a week or two.

**Comment by joeldenning** [comment]
Apologies for the month-long hiatus. I looked at this just now.

Unfortunately, I don't think that I understand what problem you are reporting. My understanding is that with Angular you must provide either APP_BASE_HREF or `<base href="">`. They are listed in [Routing Basics documentation](https://angular.io/guide/router#the-basics). In coexisting-angular-microfrontends, I am putting `/` as the base href for all the apps and everything is working (see [here](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/ccb1a5592ab5516c0e526d0bfae58fb1184f9eca/app1/src/app/app-routing.module.ts#L14)). 

I see that in your project, you are setting the base href to `/app1` and `/app2` (see [here](https://github.com/kbjerke/microfrontend-communication/blob/c66245a6f2a0b4742e390515b2c0815418ef6eda/micro-apps/projects/app1/src/app/app.module.ts#L18). My recommendation would be to change them to `/` instead.

The reason why `/` is the recommended base href is because when the browser navigates to a page that doesn't have the base href, angular freaks out. That brief moment when app1 is active, but the url is `/app2` is enough for Angular to go completely bonkers if you have told it that `/app1` is the base href.

Is there a reason that you need to set the base href to something else?

Regarding the stuff you mentioned with BrowserAnimationsModule, that seems separate from any base href stuff? Maybe related to https://github.com/CanopyTax/single-spa-angular/issues/60?

**Comment by kbjerke** [comment]
Seems like if I change app1 and app2 to "/", then the "micro-app" won't even load. It just redirects to the root path.

**Comment by joeldenning** [comment]
update your other routes to have `/app1/` in them or `/app2`. So the base route is empty, but the actual routes have the prefix in them

**Comment by kbjerke** [comment]
Your suggestion worked, I may have misunderstood you previously. Appreciate the response. Closing it :)

**Comment by jualoppaz** [comment]
Hi! @joeldenning . I have just experimented the same error with my app https://single-spa-with-npm-packages.herokuapp.com (credentials **admin / 12345**) in the Angular section, and I had to set the **APP_BASE_HREF** property to / and add the /angular prefix in every router links and routes definitions as @kbjerke had.

I didn't experiment this issue with **Vue**, so it seems to be an **Angular Router** issue. I think it would be a great idea to document this fact in https://single-spa.js.org/docs/ecosystem-angular/ page during this issue persist.

Thank you so much for the workaround.

**Comment by joeldenning** [comment]
Feel free to PR the docs with this
