### ISSUE TITLE
Uncaught TypeError: Cannot read property 'injector' of undefined at single-spa-angular.js:90

### ISSUE THREAD

**Issue by joyfulelement** [CanopyTax/single-spa-angular#65]
First of all, wanted to thank to the author for creating `single-spa` libraries. Have been trying it out from the last couple days, but now hitting this glitch without much progress. Getting this issue when attempt to load the basic Angular app with root application.

### Reproduce Steps
1. Generated an Angular App with [Angular CLI](https://github.com/angular/angular-cli) version 7.3.8.
2. Run `ng add single-spa-angular@beta` (`3.0.0-beta.17`) verified the corresponding [changes](https://github.com/CanopyTax/single-spa-angular#installation) and added both `libraryName` and `libraryTarget`
```
...
"architect": {
        "build": {
          "builder": "single-spa-angular:build",
          "options": {
                             "libraryName": "appAngular1",
                             "libraryTarget": "umd",
                             ...
                             }
           ...
           }
       ...
}
...
```
3. Setup an static server serving `main.js` from this Angular App
4. Using another root application to loads this Angular app with `single-spa` (i.e. `singleSpa.registerApplication('appAngular1', () => ...`) with `global[appAngular1].default;`

### Debugging

![localhost_8085_appAngular1](https://user-images.githubusercontent.com/5963818/57087319-c8889300-6ccd-11e9-8a07-3ea9c1dc68cc.png)

The attempt to debug found that `opts.bootstrappedModule` is `undefined` at line 90 in `unmount`. While the initialization code `opts.bootstrappedModule = module;` at line 80 in `mount` never got invoked, perhaps the reason why it was undefined. But not sure why the `mount` call didn't complete? 

Any guidance about how to move beyond this issue is highly appreciated.

![Screen Shot 2019-05-02 at 11 32 40 AM](https://user-images.githubusercontent.com/5963818/57087456-12717900-6cce-11e9-88ca-b79265c2733a.png)

**Comment by joeldenning** [comment]
Hi Kevin, thanks for reporting this issue with so much detail.

> line 80 in mount never got invoked, perhaps the reason why it was undefined. But not sure why the mount call didn't complete?

Is this happening during initial load, or only when you attempt to navigate away from the application? Can you confirm if the angular application is successfully mounting? Single-spa has the concept of an [application status](https://single-spa.js.org/docs/api.html#getappstatus) that tracks whether the app has successfully mounted, unmounted, etc. You can run `singleSpa.getAppStatus('appAngular1')` in the browser console to see if it's working.

From what you've reported, my guess is that single-spa is attempting to mount the application but is failing to because of the APP_BASE_HREF problem. When single-spa fails to mount the application, it immediately attempts to unmount it and then puts it into SKIP_BECAUSE_BROKEN status. My guess is that the mount is failing before opts.bootstrappedModule is set, so then when single-spa tries to unmount the application it also fails to unmount it.

To resolve this issue, let's get mounting working. Try adding the following to `app.module.ts`:

```js
[{provide: APP_BASE_HREF, useValue: '/'}]
```

See https://angular.io/api/common/APP_BASE_HREF for more info. Also see related https://github.com/CanopyTax/single-spa-angular/issues/64 where the APP_BASE_HREF problem is being discussed further.

**Comment by joyfulelement** [comment]
Hi @joeldenning : 

Thanks for getting back with the suggested solution, and you're right, the Angular App failed during the initial load to mount itself and hence unmount itself with uninitialised object.

With the newly configured `APP_BASE_HREF` in `app.module.ts`:
```
providers: [{provide: APP_BASE_HREF, useValue: '/appAngular1/'}],
```
I was able to get the Angular app mounted properly the first time 🎉 ! Thanks to your big help.

However, the Angular app hit another error with `zone.js` when it was unmounted:
![localhost_8085_appAngular1](https://user-images.githubusercontent.com/5963818/57099942-9be37400-6ceb-11e9-9649-7b5c6a7c06f6.png)
Looks like it failed at line 119.

![localhost_8085_appAngular1](https://user-images.githubusercontent.com/5963818/57099781-414a1800-6ceb-11e9-99d3-76bd8a023a37.png)
and the Angular app never returns and displayed later if I switch back to it. There is a lot of comment for line 119, not sure if I missed something along the way got get Angular App configured properly for `single-spa`, any idea?

By the way, running `singleSpa.getAppStatus('appAngular1')` on browser console would give: `Uncaught ReferenceError: singleSpa is not defined`.

**Comment by joyfulelement** [comment]
Ok, I managed to get around with this issue (similar to #48)  by adding the `BrowserAnimationsModule` to `app.module.ts`. I think what happened was when I did `ng add` I answering "yes" to the question about whether you're using `BrowserAnimationsModule`. But did not import it to the default Angular application. I guess if I answered it as no in the first place, this wouldn't be an issue.

Looks like the original issue had also been resolved, thanks for the big help @joeldenning!

One separate question about Angular app, do you know if there is a way to get Angular app to generate an asset `manifest.json` that contains property values like below?

```
{
  "main.js": "main.f7fd18d5.chunk.js",
  "main.js.map": "main.f7fd18d5.chunk.js.map"
}
```

**Comment by joeldenning** [comment]
Awesome, glad to hear that you got everything resolved.
