### ISSUE TITLE
not able to run application using v3.0.0-beta.19 

### ISSUE THREAD

**Issue by HemendPatel63** [CanopyTax/single-spa-angular#70]
Hi, @joeldenning
I have implemented single-spa angular 7 solution and it was working till v3.0.0-beta.17 release. I show the updated version today and try to implement the lazy loading with the latest version but did not get any luck. 
I have cloned the coexisting-angular-microfrontends solution on my local and follow the step under the local development section(https://github.com/joeldenning/coexisting-angular-microfrontends). 

It is giving file not fond exception. 

![image](https://user-images.githubusercontent.com/49240619/57334343-0da13080-70e5-11e9-9169-39b6339e4ea2.png)

 
![image](https://user-images.githubusercontent.com/49240619/57334211-b602c500-70e4-11e9-8428-e2f92f61beda.png)

 

Am I missing anything?

**Comment by joeldenning** [comment]
Are you able to run one app at a time, [as explained here](https://github.com/joeldenning/coexisting-angular-microfrontends#local-development----one-app-at-a-time)?

I just deleted my local copy of the repo, re-cloned it, and followed the instructions and was able to get it working. What operating system are you on? I'm on Mac.

The 404 you're getting in the browser for the HTML file is the most interesting thing about this. The request to `http://localhost:4200` should be hitting the [root-html-file server](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/package.json), which should be giving you a 200 with [the index.html file](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/index.html). One way that you could be getting a 404 would be if you ran `ng serve` in one of your terminals without specifying the correct ports. Did you run `ng serve --port 4201 --publicHost http://localhost:4201 --disable-host-check` (with the correct port per application), instead of `ng serve`? That is my best guess without other info.

**Comment by HemendPatel63** [comment]
Thank you joeldenning for your help! 

I am use windows 10. I have updated new package package but got the same issue.
I have followed below steps.

1.	Clone the apps(https://github.com/joeldenning/coexisting-angular-microfrontends).
2.	# First terminal tab
cd root-html-file
npm install
npm start
3.	# Second terminal tab
cd app1
npm install
ng serve --port 4201 --publicHost http://localhost:4201 --disable-host-check
4.	# Third terminal tab
cd app2
npm install
ng serve --port 4202 --publicHost http://localhost:4202 --disable-host-check
5.	# Fourth terminal tab
cd navbar
npm install
ng serve --port 4203 --publicHost http://localhost:4203 --disable-host-check


try to access the site using - http://localhost:4200 

Below are my terminal detail
![image](https://user-images.githubusercontent.com/49240619/57339041-6ed10000-70f5-11e9-87e1-d549e11044f3.png)

**Comment by joeldenning** [comment]
This might be windows specific, then, I've had issues in the past with the servers I'm using in root-html-file. Try the following, and let me know if any of them work:

1. Change [this line](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/package.json#L6) to not have the `/` before index.html. So it would be `light-server -s . --historyindex 'index.html' -p 4200`
2. Instead of running `npm start` inside of root-html-file, try the following: `npx http-server . -p 4200`. This has the major disadvantage that if you navigate away from the `/` route in the browser and refresh the page that you'll get a 404. But if it works for you going straight to http://localhost:4200 then we'll know that this must be an issue with [light-server](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/package.json#L11)

**Comment by HemendPatel63** [comment]
Yes, you are right. These changes are working but getting 404 when refresh the page.

**Comment by joeldenning** [comment]
Okay, so it's windows-specific, then. I just pushed [a commit](https://github.com/joeldenning/coexisting-angular-microfrontends/commit/92e8c51a097fc08e45d9facd8afac16d115ac299) that hopefully resolves this issue. Can you verify it works for you?

**Comment by HemendPatel63** [comment]
Its working but not with page refresh(404). 
![image](https://user-images.githubusercontent.com/49240619/57340013-9de97080-70f9-11e9-954a-ea620f73ac78.png)

**Comment by joeldenning** [comment]
Damn, I'll have to look into this later. Need to find a static server that works in Windows and is able to do SPA routing and just always return the index.html file. Other windows users reported that `light-server` worked, but looks like not in all cases. I'll spend some time on this later.

**Comment by joeldenning** [comment]
The issue with the serve package is reported here: https://github.com/zeit/serve/issues/525.

I will be submitting a PR to serve to fix this

**Comment by joeldenning** [comment]
Just submitted https://github.com/zeit/serve-handler/pull/89 which fill fix `serve` to work in windows. In the meantime, I have [downgraded coexisting-angular-microfrontends to 10.1.1](https://github.com/joeldenning/coexisting-angular-microfrontends/commit/7d7050c8dd02d19fc350788a7d349f465b850167), which works around the issue until that PR is merged.

Closing this since it's now working.
