### ISSUE TITLE
styles.scss conflict across micro-frontend applications

### ISSUE THREAD

**Issue by amaneer94** [CanopyTax/single-spa-angular#80]
Hi @joeldenning. Hope you are doing great.

I am facing styles scss conflict issues when my 2 or more micro frontend applications have the same CSS class names in style.scss file of every application. Sometimes styles overriding happens unexpectedly. What would be the best practice to avoid it?

**Comment by joeldenning** [comment]
Welcome to global styles 😄 

A couple options:
1) Use [component styles instead](https://angular.io/guide/component-styles#component-styles)
2) You can use a [BEM](http://getbem.com/introduction/) style of naming all of your styles.scss classes to avoid conflict. You wouldn't need to go all-in with BEM, but maybe just something like this:

```
.app1--orange {
  color: orange;
}
```

Closing this since I've answered the question. Feel free to continue discussion here or reopen if there's more to this.
