### ISSUE TITLE
Browser back button does not work when using Angular Router and Single SPA

### ISSUE THREAD

**Issue by ernestlv** [CanopyTax/single-spa-angular#86]
In Angular 7 if you use angular router to switch between a home page and details page everything works OK as long as you use "routerLink" in an anchor tag but if you click the browser back or forward button seems angular change-detection stops working. Components are rendered but Template properties are not updated.

I cloned the coexisting-angular-microfrontends repo and updated it with an example of the issue.

See -> https://github.com/ernestlv/angular-spa

**Comment by joeldenning** [comment]
Just tried this out and I saw the issue. We might need to reinstate [this hacky code](https://github.com/CanopyTax/single-spa-angular/blob/8f8304a851b7ae09416c0cf78adbd04fecc59a3c/src/single-spa-angular.js#L48-L62) to get change detection working.

Can you try adding the `applicationRef.tick()` inside of a `single-spa:routing-event` event listener and let me know if it works? Angular change detection is quite temperamental, due to ZoneJS needing to know about everything that happens. The angular router is not implemented to handle routing events that occur outside of its control, which is why it doesn't respond very well when they happen.

**Comment by ernestlv** [comment]
applicationRef.tick() did not quite work. I used ngZone.run() instead. That seems to fix the issue

check here -> https://github.com/ernestlv/angular-spa/blob/master/app2/src/main.single-spa.ts

**Comment by joeldenning** [comment]
Interesting -- I took a look at this last night as well. I'll look into Zone.run() as a solution.

**Comment by joeldenning** [comment]
Resolved via #89

**Comment by joeldenning** [comment]
Released in [3.0.0-beta.24](https://github.com/CanopyTax/single-spa-angular/releases/tag/v3.0.0-beta.24)

**Comment by ernestlv** [comment]
Hello 

I tried release 3.0.0-beta.24 but getting below error on "npm start"

ERROR in node_modules/single-spa-angular/lib/browser-lib/single-spa-angular.d.ts(1,38): error TS2307: Cannot find module 'single-spa'.

Looks like this line:
import { AppProps, LifeCycles } from 'single-spa'

is looking for "single-spa" in the node_modules of the child application.

**Comment by joeldenning** [comment]
Ah I added single-spa as a peer dependency to single-spa-angular for it's types, but yeah that won't be downloaded by default. Workaround is to `npm install single-spa` inside of your projects.

I've opened https://github.com/CanopyTax/single-spa-angular/issues/90 to track this

**Comment by ernestlv** [comment]
I am testing the NgZone.run approach. Browser back button now works OK but “single-spa:routing-event” is fired at least three times. If we have a few Angular components with several other nested components, that use @input, @output decorators. Component performance becomes very slow, after I navigated back using browser back button. However, if I use routerLink “single-spa:routing-event” is fired only once and performance is OK.
