### ISSUE TITLE
rc.0 is not backwards compatible with angular 7

### ISSUE THREAD

**Issue by petemcwilliams** [CanopyTax/single-spa-angular#93]
Was it necessary to force the package to insist on Angular 8 cli etc.  Ionic is still on Angular v7 which is causing conflicts.

**Comment by joeldenning** [comment]
I didn't "insist" on Angular 8. single-spa-angular@3.0.0-rc.0 is compatible with both Angular 7 and Angular 8. I tested it with Angular 7 three times before publishing.

You have not reported any specific error, shared a stacktrace, or a way to reproduce the error. Which makes your reported issue impossible for me to debug. Your issue frustrates me because it seems argumentative and full of assumptions while also containing no useful information that I could use to debug this.

**Comment by petemcwilliams** [comment]
```
npm install
npm WARN single-spa-angular@3.0.0-rc.0 requires a peer of @angular-builders/custom-webpack@^8 but none is installed. You must install peer dependencies yourself.
npm WARN single-spa-angular@3.0.0-rc.0 requires a peer of semver@^6.2.0 but none is installed. You must install peer dependencies yourself.

npm install @angular-builders/custom-webpack@^8
npm WARN @angular-builders/custom-webpack@8.0.2 requires a peer of @angular-devkit/build-angular@>=0.800.0 but none is installed. You must install peer dependencies yourself.
npm WARN single-spa-angular@3.0.0-rc.0 requires a peer of semver@^6.2.0 but none is installed. You must install peer dependencies yourself.

npm install @angular-devkit/build-angular@^0.800.0
npm WARN single-spa-angular@3.0.0-rc.0 requires a peer of semver@^6.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.800.6 requires a peer of @angular/compiler-cli@>=8.0.0-beta.0 < 9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@8.0.6 requires a peer of @angular/compiler-cli@>=8.0.0-beta.0 < 9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@8.0.6 requires a peer of typescript@>=3.4 < 3.5 but none is installed. You must install peer dependencies yourself.
```
etc

**Comment by joeldenning** [comment]
Those are warnings, not errors.

I am trying this out again locally to see if I can find an error. Thus far, I ran into an error that is not what you showed in your output. The error is related to a difference between my local development flow with `npm link` and what happens when it's not local development.

**Comment by petemcwilliams** [comment]
Ok, I accept they are warnings rather than errors, they do concern me though, I would expect if a module author is allowing other versions of third party packages then there should not be the warnings indicating that a later version of the software is not installed.

I did not mean to seem argumentative or wind you up, if you read the words in their exact meaning then it is more precise than argumentative.

I did not provide a stack trace as I thought the issue would be easy to see, it is written in your Package.json file.

**Comment by joeldenning** [comment]
Interpreting written text can be hard.

However, you doubling down and saying that your words had a "precise" meaning is also frustrating. Your original post was (1) very unclear with no relevant information contained within it, (2) based on a false assumption, and (3) complaining about and accusing the maintainers of this project ("was it necessary to insist"). You have indicated that I just didn't read your precise words carefully enough, which misses the point. The point is that you should (1) provide helpful information when creating a Github issue, (2) read release notes and documentation while not making assumptions, and (3) show appreciation for volunteer open source maintainers instead of complaining about them. Saying "ng add single-spa-angular@beta is failing in Angular 7" would have met that criteria.

I have found an issue related to Angular 7 and will release rc.1 with a fix.

**Comment by joeldenning** [comment]
single-spa-angular@3.0.0-rc.1 is released with a fix for this https://github.com/CanopyTax/single-spa-angular/releases/tag/v3.0.0-rc.1
