### ISSUE TITLE
What is the best way to notify the user that one or many applications are updated on server and the user needs to reload (hard-reload) the browser?

### ISSUE THREAD

**Issue by amaneer94** [CanopyTax/single-spa-angular#96]
As we know that the co-existing applications are cached. The previous version of the applications keeps showing until we hard-reload the browser (Ctrl + F5). Is there any way we can notify the end user that new version of that particular application is updated and he/she needs to hard reload the browser.

**Comment by joeldenning** [comment]
A couple options:

1) Put the code for each service into a directory with the commit hash. See https://app.staging.jumpsoftware.com/import-map.json, https://openmrs-spa.org/import-map.json, and https://cdn.canopytax.com/sofe-manifest.json for import maps that use this method. See https://github.com/openmrs/openmrs-esm-root-config/blob/master/.travis.yml and https://travis-ci.org/openmrs/openmrs-esm-root-config for an example of how this can be done in a CI. Angular CLI itself has ways of generating unique filenames, to via flags to `ng build`

2) Use [etag headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) on the js files which will let you keep the same file name but still control when the browser cache is busted.

I'm closing this issue since I think I've answered the question, but feel free to comment further for more discussion or reopen
